# Generated by Django 2.2 on 2020-05-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20200516_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='purchased',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='date_joined',
        ),
        migrations.CreateModel(
            name='gdlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gd_link_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
            ],
        ),
    ]
